### ISSUE TITLE
Upper case in "Desired Username" means they cannot be found later.

### ISSUE THREAD

**Issue by HamishMacEwan** [fiatjaf/satdress#10]
After creating `User21952` it couldn't be found (though creating user21952 was blocked.)
```
:~/bin/satdress$ PORT=17422 DOMAIN=merak-4.BitID.nz SECRET='SECRET' SITE_OWNER_URL=https://t.me/user21952 SITE_OWNER_NAME=@user21952 SITE_NAME=BitID ./satdress
<nil> DBG listening addr=0.0.0.0:17422
<nil> DBG generating invoice backend={"Cert":"","Host":"https://lnbits.com","Key":"[]"} description_hash=[] msatoshi=1000
<nil> DBG &{ lnbits https://lnbits.com []}
<nil> DBG {"Name":"","Kind":"lnbits","Host":"https://lnbits.com","Key":"[]","Pak":"","Waki":""}
<nil> ERR failed to get name error="pebble: not found" name=user21952

```

This behaviour seems to depend on the payer's wallet.  

https://lightningdecoder.com/PaywallStuff@payaddress.co fails but 

`/send 1337 PaywallStuff@payaddress.co`

succeeds:

```
payaddress.co says:
Payment received!
```

However

`/send 1337 paywallstuff@payaddress.co`

fails
`payaddress.co lnurl error: failed to get name paywallstuff`

**Comment by fiatjaf** [comment]
This was fixed in e2945ff375743ccf93429f69158e11335ecb099b I believe.
