### ISSUE TITLE
Suggestion: Display test invoice with PIN embedded on /grab response page

### ISSUE THREAD

**Issue by HamishMacEwan** [fiatjaf/satdress#12]
Minor niggle but the unsettled 1 sat invoices generated during the testing of the registration are annoying.

Further, could the test invoice include the PIN, and be displayed so that the registrant can pay it and receive a notice of the PIN in their transaction history.

**Comment by fiatjaf** [comment]
Good idea.

**Comment by andrerfneves** [comment]
This builds on my thoughts that we need to have a SUCCESS page that the user gets redirected to. I can add UI when this page exists. Is /grab the one I need to edit?

**Comment by fiatjaf** [comment]
@andrerfneves If you can make an HTML file for it with the desired value placeholders (and VueJS?) like index.html I can just plug it in later. I'm not sure what to put on that page so that would be better.

**Comment by andrerfneves** [comment]
I will go ahead and replicate the setup for index.html into success.html. I will also create an error.html page so you can use in case something goes wrong and pass a random message.

Not sure i totally get the QR code recommendation here. What should be in there? And what should the flow really look like?

**Comment by fiatjaf** [comment]
I've went ahead and made a multi-page setup. We can tweak this later.
