### ISSUE TITLE
Version 0.3.0 quirks

### ISSUE THREAD

**Issue by HamishMacEwan** [fiatjaf/satdress#19]
Thanks very much for the PINvoice (PIN in invoice)!

Note: "username@domain.com" rather than substitution of actual values

![chrome_GgiPktMZES redacted](https://user-images.githubusercontent.com/388061/131230452-2544b780-cc44-4edd-9020-0fc638ea7ab2.png)

When there's an error e.g.:

`<nil> DBG invoice generation error="Post \"https://lnbits.com/api/v1/payments\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" backend={"Cert":"","Host":"https://lnbits.com","Key":"83ce983075154a348ffdb9b1490b7be0"} bolt11= msatoshi=1000`

and you go back from `/grab` the form is not restored.  

![image](https://user-images.githubusercontent.com/388061/131230438-754c8259-4a62-4639-ab25-ad024d6a06a2.png)

**Comment by fiatjaf** [comment]
Yes, I know. Tried to fix that but with Vue it was impossible. @andrerfneves's new React frontend should not have these issues. I'll close this one for now.
