### ISSUE TITLE
Minor quirks

### ISSUE THREAD

**Issue by HamishMacEwan** [fiatjaf/satdress#2]
This runs it:

```
~/bin$ PORT=17422 DOMAIN=Satdress.BitID.nz SECRET='REDACTED' SITE_OWNER_URL=https://t.me/user21952 SITE_OWNER_NAME=@user21952 SITE_NAME=BitID ./satdress
<nil> DBG listening addr=0.0.0.0:17422
```
The result is at http://135.125.129.136:17422/

1. Despite the DOMAIN setting the identifier domain is presented as `@BitID.BitID.nz` instead of `Satdress.BitID.nz`

2. Tried tType LNbits with the Host being the URL to LNBits local instance landing page (guessing that's a good place to start) and in the Key field I used the `wal=` value.

This didn't work, maybe too early.  The error was:

```
couldn't make an invoice with the given data: call to lnbits failed (500): LNbits internal error!

Traceback (most recent call last):
  File "/opt/mynode/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 151, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/opt/mynode/lnbits/venv/lib/python3.7/site-packages/quart/ap
```

Perhaps the Host should be an LNURLp link from the account, so that the user can set the range and other results.

3. The Key field reset it's name to Macaroon

4. Further attempts resulted in the Host information being ignored and the calls being attempted to the satdress host:

`http://135.125.129.136:17422/grab`

Looking  forward to the next release.

**Comment by Fittiboy** [comment]
LNbits didn't work for me either. Always causes a 500, no matter which key I use.
