### ISSUE TITLE
text/identifier and text/plain missing username

### ISSUE THREAD

**Issue by Fittiboy** [fiatjaf/satdress#3]
The json object seems to be missing the actual username:
`{"status":"OK","callback":"https://ln.fitti.io/.well-known/lnurlp/fitti","tag":"payRequest","maxSendable":100000000,"minSendable":1000,"metadata":"[[\"text/identifier\",\"@ln.fitti.io\"],[\"text/plain\",\"Satoshis to @ln.fitti.io.\"]]","commentAllowed":0}`

**Comment by andrerfneves** [comment]
Well that can't be good

**Comment by andrerfneves** [comment]
@fiatjaf

**Comment by fiatjaf** [comment]
This is fixed.
