### ISSUE TITLE
build github.com/fiatjaf/satdress: cannot find module for path embed

### ISSUE THREAD

**Issue by HamishMacEwan** [fiatjaf/satdress#6]
After:

`debian@merak-4:~/bin/satdress$ go build`

Error:

`build github.com/fiatjaf/satdress: cannot find module for path embed`

From: 
```
package main

import (
	"crypto/hmac"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"encoding/json"
```

Any tips?

**Comment by atk87a** [comment]
when I try to build I get this error:

build github.com/fiatjaf/satdress: cannot load embed: malformed module path "embed": missing dot in first path element

**Comment by fiatjaf** [comment]
You need Go version 1.16.
